### ISSUE TITLE
BagBuilder.addPayloadFile() does not construct paths within the bag's data directory when the specified path is a directory

### ISSUE THREAD

**Issue by pwinckles** [jscancella/bagging#46]
Example:

```java
var src = Files.createDirectories(Paths.get("/var/tmp/foo"));
var dst = Paths.get("/var/tmp/foo-bag");

Files.writeString(src.resolve("file.txt"), "bar");

new BagBuilder()
        .addAlgorithm("md5")
        .addPayloadFile(src)
        .bagLocation(dst)
        .write();

try (var walk = Files.walk(dst)) {
   walk.forEach(System.out::println);
}
```

Expected output:

```
/var/tmp/foo-bag
/var/tmp/foo-bag/data/foo
/var/tmp/foo-bag/data/foo/file.txt
/var/tmp/foo-bag/manifest-md5.txt
/var/tmp/foo-bag/bagit.txt
/var/tmp/foo-bag/tagmanifest-md5.txt
```

Actual output:

```
/var/tmp/foo-bag
/var/tmp/foo-bag/foo
/var/tmp/foo-bag/foo/file.txt
/var/tmp/foo-bag/manifest-md5.txt
/var/tmp/foo-bag/bagit.txt
/var/tmp/foo-bag/tagmanifest-md5.txt
```

The issue appears to be that `ManifestBuilderVistor` does not use the relative path when compiling `ManifestEntries`.

**Comment by jscancella** [comment]
This should be fixed in the next release.

**Comment by pwinckles** [comment]
Great! Thanks!

The solution here https://github.com/jscancella/bagging/commit/856a8cbf5568d6a1a4774ad3a2400613ae7a6ed6 still doesn't behave consistently with the behavior when the path is a file.

For example, this:

```java
var src = Files.createDirectories(Paths.get("/var/tmp/foo"));
var dst = Paths.get("/var/tmp/foo-bag");

Files.writeString(src.resolve("file.txt"), "bar");

new BagBuilder()
        .addAlgorithm("md5")
        .addPayloadFile(src, "data/bar")
        .bagLocation(dst)
        .write();

try (var walk = Files.walk(dst)) {
    walk.forEach(System.out::println);
}
```

Produces:

```
/var/tmp/foo-bag
/var/tmp/foo-bag/manifest-md5.txt
/var/tmp/foo-bag/bagit.txt
/var/tmp/foo-bag/data
/var/tmp/foo-bag/data/foo
/var/tmp/foo-bag/data/foo/file.txt
/var/tmp/foo-bag/tagmanifest-md5.txt
```

Rather than:

```
/var/tmp/foo-bag
/var/tmp/foo-bag/manifest-md5.txt
/var/tmp/foo-bag/bagit.txt
/var/tmp/foo-bag/data
/var/tmp/foo-bag/data/bar/foo
/var/tmp/foo-bag/data/bar/foo/file.txt
/var/tmp/foo-bag/tagmanifest-md5.txt
```

But, the solution in that commit is good enough for me, as I presently have no intention to use the other API.

**Comment by jscancella** [comment]
```
new BagBuilder()
        .addAlgorithm("md5")
        .addPayloadFile(src, "data/bar")
        .bagLocation(dst)
        .write();
```
for the `addPayloadFile(src, "data/bar")` you shouldn't specify the data directory as that is implied. I will add another test case and see if I can track down where the error is. Thanks for reporting these errors!

**Comment by jscancella** [comment]
@pwinckles do you mind testing again as I believe I have fixed it properly now?
